//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KROZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Character()
        {
            this.Item = new HashSet<Item>();
        }
    
        public int ID { get; set; }
        public int currentCell_ID { get; set; }
        public string Name { get; set; }
        public string Genre { get; set; }
        public int HP { get; set; }
        public int MaxHP { get; set; }
        public int Level { get; set; }
    
        public virtual Cell Cell { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Item { get; set; }
        public virtual Monster Monster { get; set; }
        public virtual Player Player { get; set; }
    }
}
