//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KROZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ID { get; set; }
        public Nullable<int> Character_ID { get; set; }
        public string Name { get; set; }
    
        public virtual Character Character { get; set; }
        public virtual UsableItem UsableItem { get; set; }
        public virtual Weapon Weapon { get; set; }
    }
}
