//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KROZ
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class krozEntities : DbContext
    {
        public krozEntities()
            : base("name=krozEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cell> Cell { get; set; }
        public virtual DbSet<Character> Character { get; set; }
        public virtual DbSet<Inventory> Inventory { get; set; }
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<Map> Map { get; set; }
        public virtual DbSet<Monster> Monster { get; set; }
        public virtual DbSet<Player> Player { get; set; }
        public virtual DbSet<UsableItem> UsableItem { get; set; }
        public virtual DbSet<Weapon> Weapon { get; set; }
    }
}
